apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: panagiotishua/springapp
          ports:
            - containerPort: 8080
          env:
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: secrets
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: secrets
                  key: DB_PASSWORD

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: secrets
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: secrets
                  key: DB_PORT

            - name: MAILHOG_HOST
              valueFrom:
                configMapKeyRef:
                  name: secrets
                  key: MAILHOG_HOST

---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: ClusterIP