---
- hosts: kubernetes-vm
  vars:
    user: kubernetes
  tasks:
    - name: Install microk8s with option --classic
      become: true
      community.general.snap:
        name: microk8s
        classic: yes
    - name: Allow pod-to-pod and pod-to-internet communication
      become: true
      shell:  ufw allow in on eth0 && sudo ufw allow out on eth0 && ufw default allow routed
    - name: Enable plugins
      become: true
      shell: microk8s.enable dashboard dns storage ingress
    - name: Add user to microk8s
      become: true
      shell: usermod -a -G microk8s {{ user }}
    - name: Change .kube ~/.owner
      become: true
      shell: chown -f -R {{ user }} ~/.kube
    - name: Add microk8s.kubectl alias for user
      lineinfile:
        path=/home/{{user}}/.profile
        line="alias k='microk8s.kubectl'"
        owner={{ user }}
        regexp='^alias k='microk8s.kubectl'$'
        state=present
        insertafter=EOF
        create=True
    - name: Copy configuration files
      copy:
        src: ../kubernetes/{{ item }}
        dest: /home/{{ user }}
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0664'
      loop:
        - db-deployment.yaml
        - app-deployment.yaml
        - ingress.yaml
        - mailhog-deployment.yaml
        - mailhog-ingress.yaml
    - name: Deploy
      shell: microk8s.kubectl apply -f "{{item}}"
      loop:
        - db-deployment.yaml
        - mailhog-deployment.yaml
        - mailhog-ingress.yaml
        - app-deployment.yaml
        - ingress.yaml
